/** Optional suggested values; tags accept any free-form string. */
export const TAXONOMIES = {
  category: [
    'tops',
    'bottoms',
    'dresses',
    'outerwear',
    'shoes',
    'accessories',
    'bags',
    'activewear',
  ],
  color: [
    'black',
    'white',
    'gray',
    'navy',
    'blue',
    'green',
    'red',
    'pink',
    'yellow',
    'orange',
    'brown',
    'beige',
    'purple',
    'multicolor',
  ],
  season: ['spring', 'summer', 'fall', 'winter', 'all_season'],
  occasion: ['casual', 'work', 'formal', 'party', 'date', 'travel', 'sport'],
  style: [
    'minimal',
    'classic',
    'streetwear',
    'boho',
    'preppy',
    'athleisure',
    'vintage',
  ],
  material: [
    'cotton',
    'linen',
    'wool',
    'silk',
    'denim',
    'leather',
    'synthetic',
    'knit',
  ],
  pattern: [
    'solid',
    'striped',
    'checked',
    'floral',
    'printed',
    'graphic',
    'other',
  ],
  formality: [
    'very_casual',
    'casual',
    'smart_casual',
    'business',
    'formal',
  ],
} as const;

export type TaxonomyName = keyof typeof TAXONOMIES;
